### ISSUE TITLE
Warnings when using with slimit package

### ISSUE THREAD

**Issue by gsingh93** [dabeaz/ply#82]
I get the following warnings when I use the slimit package.

```
WARNING: Couldn't write lextab module <module 'slimit.lextab' from '/usr/lib/python2.7/site-packages/slimit/lextab.pyc'>. Won't overwrite existing lextab module
WARNING: yacc table file version is out of date
WARNING: Token 'IMPORT' defined, but not used
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'ENUM' defined, but not used
WARNING: Token 'EXTENDS' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: Token 'CONST' defined, but not used
WARNING: Token 'EXPORT' defined, but not used
WARNING: Token 'CLASS' defined, but not used
WARNING: Token 'SUPER' defined, but not used
WARNING: There are 10 unused tokens
WARNING: Couldn't create <module 'slimit.yacctab' from '/usr/lib/python2.7/site-packages/slimit/yacctab.pyc'>. Won't overwrite existing tabmodule
```

I get this with ply 3.7 and 3.8. How can I fix this?

**Comment by ruda-almeida** [comment]
According to @dabeaz on #63 this should have been fixed on ply 3.7, but I am also having this issue.

**Comment by dabeaz** [comment]
The error message says that the yacc table file is out of date.   The fix to this problem is to delete the existing lexer/parser table files and rerun PLY.

**Comment by scuml** [comment]
Fixed it with:

    pip uninstall ply
    pip install ply==3.4

**Comment by johnyf** [comment]
I had a similar problem, where re-installing with `pip` did not fix the problem, because `pip` was caching a wheel for that package (I think). After using `--no-cache-dir` with `pip`, the `setup.py` was re-run, updating the tables.

**Comment by eneagu** [comment]
sudo python
>>>from slimit.parser import Parser
>>>Parser()
